language: node_js
node_js:
- 0.12
script: ./scripts/build.sh
before_deploy: ./scripts/release.sh
deploy:
  provider: npm
  email: jj@geewax.org
  api_key:
    secure: fdOPQR6qYjw7vIRtQgbIGZnM3/OOXNHznYEObtTkUXl4mpVIstZ7gTn6MVHTYeAqpBtLpIIXGxocwLqie1HIbs5tSMWmY+7yzi2Igb9xDWlq36fBOIUbv9FkSRXjgQrtvKFdsJlgTIpTtK3KHCcY/9o/YCTYgj2ejMWhDq1zo3c=
  on:
    tags: true
    repo: GoogleCloudPlatform/gcloud-node
    all_branches: true
sudo: false
